### ISSUE TITLE
Geocoder module: Add clearing button to remove search text

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/wegue#108]
Add a clearing button to easily remove the search text from the textfield of the Geocoder module.

See #29: For the general concept of the Geocoder module and #95 for the current implementation and its discussion.

**Comment by justb4** [comment]
Ok, see https://v15.vuetifyjs.com/en/components/combobox, hopefully this is as simple as to have the `clearable` option as `prop`. (Good first issue then).
