### ISSUE TITLE
AppLogo and AppHeader-title: provide for optional hyperlink

### ISSUE THREAD

**Issue by justb4** [meggsimum/wegue#114]
In cases the `AppLogo` Wegue component implemented in [AppLogo.vue](https://github.com/meggsimum/wegue/blob/master/src/components/AppLogo.vue) should provide a hyperlink for when a user clicks the logo. This feature should be optional via a new AppLogo config attribute `logoLink`. 
Possibly also the link target like `"_blank"` could be configured in `logoLinkTarget`.

Also can be applied to the `title` (`v-toolbar-title`) in the AppHeader  implemented in [AppHeader.vue](https://github.com/meggsimum/wegue/blob/master/src/components/AppHeader.vue): provide optional config for `titleLink` and `titleLinkTarget`.

**Comment by justb4** [comment]
Rethinking: both  [AppLogo.vue](https://github.com/meggsimum/wegue/blob/master/src/components/AppLogo.vue)  and the `title` in [AppHeader.vue](https://github.com/meggsimum/wegue/blob/master/src/components/AppHeader.vue) could be made more flexible to configure if like [AppFooter.vue](https://github.com/meggsimum/wegue/blob/master/src/components/AppFooter.vue) regular HTML content would be allowed in the configuration. Like: in AppFooter.vue:

```
<span class="wgu-footer-left" v-html="footerTextLeft"></span>
```

`AppHeader` ``title`` could be simply: 
` <v-toolbar-title><span v-html="title"/></v-toolbar-title>`. Adding a `title` with a link in the config:
```
  "title": "<a href='https://github.com/meggsimum/wegue' target='_blank' style='text-decoration: none; color: white'>Vue.js / OpenLayers WebGIS</a>",
```
(though we would need styling or by default disable link styling in Component Style section).

Another issue is that [AppLogo.vue](https://github.com/meggsimum/wegue/blob/master/src/components/AppLogo.vue)  uses [Vuetify <v-avatar>](https://v15.vuetifyjs.com/en/components/avatars), allowing only square images and no links. So a rectangular image is squared/gets distorted.

**Comment by chrismayer** [comment]
Maybe we should split this in separate issues. One regarding the title and one caring about a more flexible AppLogo component.

**Comment by justb4** [comment]
> Maybe we should split this in separate issues. One regarding the title and one caring about a more flexible AppLogo component. So we do not mixup thing.
> 
Yes makes sense. At first thought the issue was too trivial.

> In general: Do you see any advantage just to have a Vue component as HTML wrapper. For title this might make sense as we do in the Footer component. But for the AppLogo this could be done easily at application level instead of defining a HTML in the config. Maybe a hybrid approach would be cool here. Allowing to just provide an image URL in the config for easy usage (for non-tech people just configuring an app) would be nice and for advanced users providing a custom HTML is also allowed. Not sure how to differentiate between those.
Well, the current PR has the hybrid approach, see [AppLogo.vue there](https://github.com/meggsimum/wegue/blob/440b1cef6bfc45f118f8d59aa4ccf32002fca60f/src/components/AppLogo.vue) but it does not feel very elegant. But do you agree that the logo as `v-avatar` (square) is somewhat limiting?

This issue and the general app-development workflow with Wegue, plus some code I saw in a branch "App Folder Config": https://github.com/chrismayer/wegue/blob/app-fldr-conf/src/main.js#L47 made me think of a broader solution for Wegue (starter-)app development we can discuss via a new issue or on Gitter. I am happy to explain my proposals.

**Comment by chrismayer** [comment]
> But do you agree that the logo as v-avatar (square) is somewhat limiting?

Agree, I created #117 for that. Further discussions should be done there.

**Comment by chrismayer** [comment]
For the title improvement I also created a separate issue #118.

> This issue and the general app-development workflow with Wegue, plus some code I saw in a branch "App Folder Config": https://github.com/chrismayer/wegue/blob/app-fldr-conf/src/main.js#L47 made me think of a broader solution for Wegue (starter-)app development we can discuss via a new issue or on Gitter. I am happy to explain my proposals.

Sure, happy to hear your ideas.

**Comment by justb4** [comment]
Ok, so I close this issue as there is #117 and #118 . And will get back on Wegue app-development workflows.
