### ISSUE TITLE
Application config and directory restructure

### ISSUE THREAD

**Issue by justb4** [meggsimum/wegue#130]
This issue relates/depends on to #98 but goes a bit further. 

A typical Wegue project will clone the Wegue GH repo, add both new custom (Vue) components and/or modify core Wegue code and components. Currently this implies changes to files under the `src/` dir. Merging-in changes from upstream Wegue GH repo later gets more and more tedious and error-prone.

Ideally we would not need to touch any files under `src/` but develop app-specific components and other resources under the `app/` tree. This should also be a step towards making Wegue a real app-framework with a CLI to create a starter-app under any other dir/ repo i.s.o. within a clone of the Wegue repo under `app/`. The advantage of this process though is that one constantly have all files at disposal, also e.g. within debuggers.

Via this issue I propose the following changes:

* remove `app/.gitignore`
* place `app-conf.json` under `app/static` dir (via #98)
* implement/merge [the simple solution](https://github.com/chrismayer/wegue/blob/app-fldr-conf/src/main.js#L47) which first first looks for app config under app-dir.  
* put app-specific components and if possible modified Wegue components under `app`-dir
* make an `app/components/` shadow dir with app-specific/Wegue-app-specific-modified components
* make `app/static` a shadow dir from `static/`: with app-specific resources (e.g. css, icons etc) that overwrites `static` in builds
* reference both `app` and `src` Vue components (requires build config changes)
* extend Wegue CLI `npm run init:app`

For the latter the CLI `npm run init:app` needs to copy the following Wegue  files under `app`-dir: `WguAppTemplate, AppFooter, AppHeader`. These will be app-specific anyway at some point.

Note that we already successfully applied this restructuring within the Geolicious project for NPLH. Need to see what is the best strategy to pull-in this work via https://github.com/Geolicious/wegue. 
That huge change costed little dev-time, and helps with future Wegue dev-workflows, much the way e.g. many template-systems like Django work (shadowing a subset of files with a searchpath).

**Comment by justb4** [comment]
Think we can close?

**Comment by chrismayer** [comment]
Yes, I'll close it
