### ISSUE TITLE
Map moves when hovering over features close to border

### ISSUE THREAD

**Issue by JakobMiksch** [meggsimum/wegue#135]
When a feature next to the map border is hovered, the map moves in order to display the whole pop up. See this demo:

![bug](https://user-images.githubusercontent.com/15704517/86277618-49dffc00-bbd7-11ea-8fe4-2e00b4b16e44.gif)

**Comment by chrismayer** [comment]
This is more a feature than a bug IMHO. Maybe making this configurable would be an option?

**Comment by JakobMiksch** [comment]
I agree, I just noticed this effect and was surprised, that's why I opened this issue. 

Making it configurable is for sure a good idea  - assuming if it is an easy fix.
Otherwise we could simply close this issue again. I am fine with both.

**Comment by chrismayer** [comment]
To be honest I am not sure if this is easy to prevent. We can leave this open for a while. If nothing happens in a suitable amount of time we can close.

**Comment by fschmenger** [comment]
I think this can be altered very simply by removing the `autoPan` and `autoPanAnimation` properties of the respective OL overlay. 

https://github.com/meggsimum/wegue/blob/c18e5b6da65f5a839dfff6580e272f0de780aaac/src/components/ol/Map.vue#L277-L285

I'm currently working on a generalized feature hover implementation. In the process I will also provide a vuetify based `MapOverlay` abstraction, so e.g. customized hover tooltips will be easy to implement with vuetify on-board equipment and can then be associated with specific layers.

I will preserve the autopan behaviour for now and we can discuss in the process, whether we like it or not.

**Comment by JakobMiksch** [comment]
closing. If anyone wants to change that behavior this can be done per individual application as described above
