### ISSUE TITLE
Gallery / Success Stories

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/wegue#137]
We should add a section "Gallery" (or similar), which shows projects done with Wegue in the README and the upcoming website.

Therefore we should collect addresses / references to projects build upon Wegue. Please add such references in here as comments.

**Comment by chrismayer** [comment]
https://bevinggevoeld.nl/oeds/groot/

https://www.starkregengefahr.de/baden-wuerttemberg/glems/

**Comment by justb4** [comment]
https://wegue.heron-mc.org/

**Comment by justb4** [comment]
https://map.naturpark-lueneburger-heide.de/  - how could I forget this one ;-).

**Comment by chrismayer** [comment]
If possible a one-liner as description and a link to a public source code repo (if available) would be nice to have for the given links. So we can use this on the Wegue website. Thanks for any hint / support.

**Comment by JakobMiksch** [comment]
closed with https://github.com/meggsimum/wegue/pull/167
