### ISSUE TITLE
Make online application demo available again

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/wegue#141]
Due to the fact that we deliver the new Wegue website on `gh-pages` (https://meggsimum.github.io/wegue, see #136 ), the online application demo (which was deployed there before) is not available anymore. It should be restored somewhere in our project's `gh-pages`.

**Comment by justb4** [comment]
Hmm, a bit a puzzle, also in the light of CNAME (deleted?) and a custom domain. 
Somehow we need to have docs and the demo under the same dir tree. Thinking loud I see two options:

* use the `gh-pages` branch for the website, on post-commit copy the `docs` tree to there and build/copy the demo there
* use `master` and on post-commit build/copy the demo app to the `docs` tree

In all cases I would prefer maintaining the docs on the `master` branch and the second option above. 
Lately I started using GitHub Actions over Travis, this can help with the above.

**Comment by chrismayer** [comment]
I'd also prefer the "use master and on post-commit build/copy the demo app to the docs tree" solution (if possible). I have no strong opinion whether we use Travis or github actions. Whatever does the trick is fine for me.
