### ISSUE TITLE
Fix broken deactivation of measurement tools

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/wegue#15]
While having open the measurement tool it is possible to depress both buttons (Distance and Area). But this has no effect on the measurement tool on the map. In case both buttons are deactivated the Distance tool gets activated.

![image](https://user-images.githubusercontent.com/1185547/39228799-2c2d49fc-4860-11e8-8abe-3e65adc0e202.png)

Wanted behavior: Deactivate all measure tools on the map when both buttons are depressed.

**Comment by LiliGuimaraes** [comment]
At this point, "measuretype" is checkbox styled.
Isn't correct to change for radio style (with mandatory selection)?

If it is, I'll send the PR.

**Comment by chrismayer** [comment]
Right, this should behave like a radio button, so the user cannot depress both options. But I would like to keep the UI and just change the behavior (if possible).

Would be cool, if you come up with a PR @LiliGuimaraes .

**Comment by chrismayer** [comment]
Fixed by #18
