### ISSUE TITLE
How to load BingMap?

### ISSUE THREAD

**Issue by wsyinstalling** [meggsimum/wegue#186]
I looked at the help document, but no specific instances were found. Could you give a specific demo?

**Comment by JakobMiksch** [comment]
Adding Bing as native layertype is not supported. But you can use the [XYZ layer type](https://meggsimum.github.io/wegue/#/map-layer-configuration?id=xyz) for it. It should look like this:

```
 "mapLayers": [
    {
      "type": "XYZ",
      "name": "Bing VirtualEarth",
      "url": "LINK-TO-BING-XYZ-SERVICE",
      "lid": "bing_virtualearth",
      "attributions": "ADD PROPER ATTRIBUTION"
    }
  ],
```
I guess you need an API key for it and you should attribute the layer properly.
