### ISSUE TITLE
Enable i18n

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/wegue#205]
Add a mechanism for internationalization (i18n) maybe with [vue-i18n](url), which was used in a Wegue based project solution: https://github.com/Geolicious/wegue/commit/c4af28b6fc5c97dff4baf2bae6abb30d11197cec

See also:  https://localazy.com/blog/how-to-localize-vuejs-app-with-vue-i18n-and-localazy

**Comment by fschmenger** [comment]
I can start working on this. Thanks for the link to Geolicious@c4af28b, this will get me going.

Some of the currently supported app.conf options have to be tweaked, as they're currently language specific, e.g.
* modules.title
* various options in wgu-helpwin
* layer names

Any ideas on how to resolve those are welcome.
