### ISSUE TITLE
Configuration for initial module visibility 

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/wegue#216]
It would be useful to configure a module initially visible especially when it is rendered in the sidebar.

Idea by @fschmenger from #213:
A general way to solve this could be to add some module property like 'show' to the config - this can be easily implemented for the generic module card windows.

**Comment by fschmenger** [comment]
You can assign this to me. Will be straight forward after #219 is integrated.
What name would you propose for the property?
open, show, visible, showInitially, .... ?

**Comment by chrismayer** [comment]
> What name would you propose for the app-conf.json modules property?
open, show, visible, showInitially, .... ?

Maybe `open` ?

**Comment by fschmenger** [comment]
Ok, this one is ready. However I suggest you merge in #220 first to have a stable release first.
I just found that the layer config uses the attribute 'visible', so I will use the same attribute name - I hope you don't mind.

**Comment by chrismayer** [comment]
Closed by #221
