### ISSUE TITLE
Remove no longer working layers from the configuration examples.

### ISSUE THREAD

**Issue by fschmenger** [meggsimum/wegue#226]
Ahocevar-wms (https://ahocevar.com/geoserver/wms) and Vector Tile Layer (https://ahocevar.com/geoserver/gwc/service/tms/1.0.0/ne:ne_10m_admin_0_countries@EPSG%3A900913@pbf/{z}/{x}/{-y}.pbf) seem to be no longer working:
Any request results in 502 -Bad Gateway.

I discovered this today while testing layer sources for being CORS enabled.

This could be a temporary problem. If it persists we should remove the layers from our configuration templates.

**Comment by JakobMiksch** [comment]
thanks @fschmenger good catch

**Comment by chrismayer** [comment]
Seems to work again, maybe a temporary issue. Please re-open, if it happens again. If it happens more often we have to find a substitute.

**Comment by fschmenger** [comment]
I just noticed, that the services for base layers involved in the `projected` configuration have stopped working

* `pdok-lufo-wms`: http://geodata.nationaalgeoregister.nl/luchtfoto/rgb/wms
* `brtachtergrondkaart`: https://geodata.nationaalgeoregister.nl/tiles/service/wmts/brtachtergrondkaart/EPSG:28992/{z}/{x}/{y}.png

For the latter one, this looks like it's going to be a permanent issue.
![wegue_projected_WMS](https://user-images.githubusercontent.com/46027124/142386956-e5bb7dbc-0290-4777-a8b8-70adb5cae3d1.png)

@chrismayer I changed the issue title to a general placeholder thread for broken layers. Could you please re-open, I don't have the required permissions.

**Comment by chrismayer** [comment]
@justb4 do you know somethings about the broken or gone layers `pdok-lufo-wms` and `brtachtergrondkaart` and maybe know some substitutes?

**Comment by justb4** [comment]
the services are still there, but the urls changed:

* https://service.pdok.nl/hwh/luchtfotorgb/wms/v1_0?
* https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/standaard/EPSG:28992/%(z)s/%(x)s/%(y)s.png

will provide more detail, but am not behind a computer this week.
