### ISSUE TITLE
BackgroundLayerSwitcher: Disable when no Background layers

### ISSUE THREAD

**Issue by JakobMiksch** [meggsimum/wegue#227]
Currently it it is not possible to disable the BackgroundLayerSwitcher with the config. See [comment](https://github.com/meggsimum/wegue/pull/223#issuecomment-869464003) in the pull request.

I needed to disable it in an application. **Workaround**: remove line with the component reference in `WgueAppTemplate`: https://github.com/meggsimum/wegue/blob/master/app-starter/WguAppTemplate.vue#L37

It would be useful if the switcher is disabled automatically when there is no background layer set

**Comment by fschmenger** [comment]
Hi Jakob, the simplest workaround for the time being is via css
`.wgu-bglayerswitcher {
  display: none;
}`
so you don't have to change the app template.

As already proposed by @chrismayer, we could disable the background switcher implicitly when there are no baseLayers configured. This solution would be preferred by me over a simple disable flag. The reasoning behind is that the (foreground) layer picker now excludes all baseLayers. In other words, by introducing a disable flag, we would open the door to some mis-configurations, when layers can be declared as baseLayers and visibility can no longer be toggled in the application.

Let me know, if this solution is acceptable for you.

**Comment by JakobMiksch** [comment]
@fschmenger thanks for the advice to disable the button via CSS.

I would also vote for removing the button implicitly when there is no layer marked as background layer.

This is simplest approach and hopefully helps to reduce misconfiguration

**Comment by fschmenger** [comment]
I'm currently implementing this. What I'm thinking about:

* By _disabling_ we actually talking about **hiding** the button?!
* Is there any need to show the button when there is exactly 1 background layer? For a first shot I decided to hide it too in this case - can change it if you think otherwise.
