### ISSUE TITLE
Add geocoder widget

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/wegue#29]
A search widget to query a geocoder, like [Nominatim](https://wiki.openstreetmap.org/wiki/Nominatim), would a be a very useful component. 

The UI could be a textfield  with a result list below or a (possibly) existing combobox implementation , which provides the same functionality.

![image](https://user-images.githubusercontent.com/1185547/43084034-278067d0-8e98-11e8-9fc4-ac961caca9fe.png)

**Comment by chrismayer** [comment]
Also [Photon](http://photon.komoot.de/) would be a great option to have as supported geocoder.

**Comment by justb4** [comment]
I've started on this issue. Made Geocoders in OL before, but mainly struggling with the `Vue`, in particular the `Vuetify`-part for the component:

* template: I have a `v-btn` with `search` icon as toggle
* when enabled the searchinput box expands little bit [like this example](https://codepen.io/jreyesgs/pen/EWgBGM)
* toggle works ok, also aligns with Wegue `-btn` convention for toolbar
* next: what to choose as input box, thought [v-combobox](https://vuetifyjs.com/en/components/combobox) (as I used with ExtJS) but struggling receiving events (v-on:input, v-on:keydown etc trigger nothing) and popping up suggestions. Maybe should use other widget like regular `v-text-field`?

Below is a dump of the current component:

```
<template>

  <v-toolbar-items>
    <v-combobox
      v-model="selected"
      :items="searchResults"
      :label="label"
      append-icon=""
      :dark="dark"
      :persistent-hint="persistentHint"
      :hidden="showSearch"
      @change="onUpdate"
    ></v-combobox>
    
    <v-btn @click='toggle()' icon :dark="dark" slot="activator">
      <v-icon medium>{{icon}}</v-icon>
        {{text}}
      </v-btn>
  </v-toolbar-items>

</template>

<script>
  import {Mapable} from '../../mixins/Mapable';

  export default {
    name: 'wgu-geocoder-input',
    mixins: [Mapable],
    props: {
      color: {type: String, required: false, default: 'red darken-3'},
      icon: {type: String, required: false, default: 'search'},
      text: {type: String, required: false},
      label: {type: String, required: false, default: 'Nominatim Search'},
      dark: {type: Boolean, required: false, default: false},
      persistentHint: {type: Boolean, required: false, default: true}

    },
    data () {
      return {
        selected: '',
        showSearch: true,
        searchResults: [
        ]
      }
    },
    methods: {
      toggle () {
        this.showSearch = !this.showSearch
      },
      onUpdate (e) {
        console.info('updated combo:', e);
      },
      onEnd () {
        // When all done center map, set marker etc
        const center = 'something';
        this.map.getView().setCenter(center);
      }
    },
    watch: {
      selected (value) {
        console.log(`selected=${value}`)
      }
    }
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style>
</style>

```
There is a [nice Geocoder for OL](https://github.com/jonataswalker/ol-geocoder) but is embedded in map with custom HTML/DOM.

**Comment by justb4** [comment]
Ok, got much further: trick is `:search-input.sync="search"` to get text from `v-combobox`. 

Hacked a very rough version based on https://github.com/jonataswalker/ol-geocoder (MIT license will add), see https://github.com/justb4/wegue/tree/master/src/components/search

**Comment by chrismayer** [comment]
Looks promising @justb4! I'll have a detailed view the next days. Thank you so far!

**Comment by justb4** [comment]
First rough working version, Geocoder-clients are always more involved (projections, query timeouts etc) than expected 😄 :
 
![image](https://user-images.githubusercontent.com/582630/62228237-90244e00-b3bd-11e9-9db5-0f1cbfaf3ac6.png)

* OSM Nominatim Provider (more providers like Photon planned)
* zooms to extent (bbox) of selected result
* supports re-projections

TODO:

* more Providers (Photon, Bing, Google etc)
* uses Promise with custom `jsonp`, maybe  use `axios`?
* some Providers do not render bbox attrs in result--> need `setCenter()` + `setZoom()`, but which zoom, street, country level etc.
* check naming conventions Search vs Geocoder
* (how to) pass JSON config arguments to the Vue component

**Comment by justb4** [comment]
Implementation is coming along ok. Updated TODO list above.

One item: in many Geocoder implementations a (disposable) Marker is placed at the selected location as an (config) option. This will require some extra OL stuff. I propose to leave that for now, and add later if even required.

**Comment by chrismayer** [comment]
> I propose to leave that for now, and add later if even required

Sure, we can add that later on

**Comment by chrismayer** [comment]
This is done and Geocoder is merged a long time ago. Further optimizations / enhancements should be handled in separate issues (e.g. #109)
