### ISSUE TITLE
Add ZoomToMaxExtent Button

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/wegue#7]
A button, which zooms the map to its initial center and zoom would be a nice component. The component should be named ``<ZoomToMaxExtentButton>``.

For a first step it would be OK, if it is usable in the top toolbar (``<AppHeader>``).

**Comment by LiliGuimaraes** [comment]
Hello or
I'm doing this task right now. I will soon send a pullrequest

**Comment by LiliGuimaraes** [comment]
Hello, sir!
I have tried to implement this funconality in the last few days, however, I can not understand how Vue.js works for this.
I know how to implement the ZoomToExtend control functionality of OPL4, however inside a function that returns to the center I could not.
I tested with getCenter, SetCenter, several things, but I could not.
But I really, really, really want to know  !!
Someone help me?

Next, the code I tried to implement following an example of Vue.

`<template>
  <div class="">
    <v-btn icon @click="">
      <v-icon medium>{{icon}}</v-icon>
      {{text}}
    </v-btn>
  </div>
</template>

<script>

import { WguEventBus } from '../../WguEventBus.js'

export default {
  name: 'wgu-toggle-zoom-max-extent-button',
  components: {
  },
  data: function () {
    return {
      show: false,
      icon: 'android',
      text: '',
      left: '100px',
      top: '200px'
    }
  },
  created () {
      // Listen to the ol-map-mounted event and receive the OL map instance
    WguEventBus.$on('ol-map-mounted', (olMap) => {
      this.center = [0, 0];
      this.map.getCenter();
      return this.map.Center();
    });
  }
}
</script>`

**Comment by chrismayer** [comment]
Hi @LiliGuimaraes,

thanks for your will to tackle this. Here is some code sceleton, how it should work:

```
<template>

  <div class="">

    <v-btn icon @click="onClick">
      <v-icon>{{icon}}</v-icon>
      {{text}}
    </v-btn>

  </div>

</template>

<script>

export default {
  name: 'wgu-zoomtomaxextentbutton',
  props: {
    icon: {type: String, required: false},
    text: {type: String, required: false}
  },
    created () {
      var me = this
      // Listen to the ol-map-mounted event and receive the OL map instance
      WguEventBus.$on('ol-map-mounted', function (olMap) {
        // make the OL map accesible in this component
        me.map = olMap;
      });
    },
  methods: {
    onClick () {
      //TODO derive correct initial zoom and center
      // const initialCenter = ...
      // const initalZoom = ...
      this.map.getView().setCenter(initialCenter);
      this.map.getView().setZoom(initalZoom);
    }
  }
}

</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style>
</style>

``` 
I am not sure at the moment how the correct values can be derived. Maybe it is possible to access the ``center`` and ``zoom`` propertiesof the ``wgu-map`` component. If this is not possible we can apply these values to our OL map instance. Maybe you can have a quick look if you can access the values by ``wgu-map``. Hope this helps a bit.

**Comment by chrismayer** [comment]
**Update for the detection of initial map-zoom and map-center:**

In the meantime the initial map-zoom and map-center can be accessed by the ``$appConfig`` object, which has been introduced by 6b76905fafc41014b8241f2090e31102d25c2073. So now the values can be accessd by 

```javascript
this.$appConfig.mapZoom
```
and 
```javascript
this.$appConfig.mapCenter
```
See ``src/components/ol/Map.vue`` for more information.

**Comment by chrismayer** [comment]
Is here still anything ongoing by you @LiliGuimaraes?

**Comment by LiliGuimaraes** [comment]
Hello, I could not solve this problem because of work. I would like to try to continue to help with the project on other issues, if possible. Sorry about that.

**Comment by chrismayer** [comment]
No problem @LiliGuimaraes. As said I will come up with this in a few days since I need it for a project. If you want you can check my final solution and compare it with your tries, so you'll get a bit deeper into the topic.
