### ISSUE TITLE
Add (dev) discussion space for Wegue project

### ISSUE THREAD

**Issue by justb4** [meggsimum/wegue#85]
Currently the contact for information/support for Wegue is an email address. In order to engage at least developers, having some kind of common discussion space would be nice. 

A mailing list is IMHO a bit old-fashioned. I use/like [Gitter](https://gitter.im/) a lot, as it can be coupled to a single GH repo, also listing repo-activities like commits etc. But also Slack or even Telegram-groups are used these days.  @chrismayer you can make a choice what suits you if you think such a discussion space is useful.

**Comment by chrismayer** [comment]
I agree that a dev talk space besides an email-adress for the project would be nice.
I am a bit afraid that a kind of chat implies immediate responses all the time. Email-List are more asynchronous and no one would expect to have an immediate response. Reason is that I cannot hang around at the chat channel all the time. The question is: Will it be expected or can such a chat platform like gitter also used more asynchronous or will it frustrate people, who are writing there?

From the technical side: I did not use any of the platforms you listed. So I would be happy if you could recommend something. The integration of gitter into github (or vice versa) sounds good. Any disadvantages?

**Comment by justb4** [comment]
Ok, understood. I think Gitter is mostly geared at developers and more relaxed in that folks don't expect immediate responses (as they are all busy developers!) like in regular chat channels, also since the history is largely preserved. Plus any GH activity (e.g. commits, issues) can be displayed as option, so one can see that something is going on.My thought was that it would maybe even save you time, for e.g. announcements (like e.g. you are working on personal  branch for 1.0), instead having 1-1 emails.

**Comment by chrismayer** [comment]
OK, thanks for the details. Sounds like it would be worth a try using gitter.

**Comment by chrismayer** [comment]
I just created a [gitter community for Wegue](https://gitter.im/wegue/community). @justb4 you should have received an invitation.

**Comment by justb4** [comment]
Super, joined! You may want to add now or later a badge to the README.md like
[![Join the chat at https://gitter.im/wegue/community](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/wegue/community) 

```
[![Join the chat at https://gitter.im/wegue/community](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/wegue/community) 
```

and you may want to couple GitHub events to the Gitter room, in Settings.

**Comment by chrismayer** [comment]
Badge is added to the README.

I also registered some events. Not sure if it works correctly since we had no events so far. But we will see...

**Comment by justb4** [comment]
Good! Events work, seen mention of your last comment. Closing this issue, ok? Trying get some (Heron-) devs engaged. Let's see how this goes.
