### ISSUE TITLE
OSM basemap blurry

### ISSUE THREAD

**Issue by JakobMiksch** [meggsimum/wegue#96]
| [Wegue](https://meggsimum.github.io/wegue/)                    | [osm.org](www.osm.org)                     |
| -------------------------------- | --------------------------- |
|![image](https://user-images.githubusercontent.com/15704517/73185493-72dafd00-411e-11ea-84e9-36b61ff53fae.png) | ![image](https://user-images.githubusercontent.com/15704517/73185511-7bcbce80-411e-11ea-85d6-61fef717eb73.png) |

The OSM basemap looks more blurry on Wegue compared to the OpenStreetMap website

**Comment by JakobMiksch** [comment]
maybe this is caused by [me.map.updateSize();](https://github.com/meggsimum/wegue/blob/master/src/components/ol/Map.vue#L48)
just an idea ...

**Comment by chrismayer** [comment]
Thanks @JakobMiksch for reporting this. Not sure what happens there. Maybe a DOM element overlaying the map canvas accidentally?

**Comment by JakobMiksch** [comment]
the bug does not exist anymore
