### ISSUE TITLE
Config-file location

### ISSUE THREAD

**Issue by JakobMiksch** [meggsimum/wegue#98]
Currently the config file must be placed in the `static` folder, whereas the rest of application-specific code is located in `app`. 

Therefore, it would be clearer to also move the config file to the `app` folder. Ideally the `init:app` script should create this initial config file. So, the user can immediately start the application.

**Comment by justb4** [comment]
Agree, there is also issues with merging upstream into a clone. Possibly `main.js` could first look in `app` and then `static` for a config as a saw in @chrismayer branch: https://github.com/chrismayer/wegue/blob/app-fldr-conf/src/main.js#L47.

Placing a starter config under `app/` could be also something `init:app` could do...

**Comment by chrismayer** [comment]
Yes, the development in https://github.com/chrismayer/wegue/blob/app-fldr-conf/src/main.js#L47 is based on this issue. I should have pulled it to me. Done by now :wink: 

 > Placing a starter config under app/ could be also something init:app could do...

That was the plan as described by @JakobMiksch in the initial description of the issue: "Ideally the init:app script should create this initial config file. So, the user can immediately start the application"

**Comment by justb4** [comment]
Think we can close this one.
