### ISSUE TITLE
Support drag 'n drop of spatial files

### ISSUE THREAD

**Issue by chrismayer** [meggsimum/wegue#99]
Since OpenLayers supports drag 'n drop for spatial data it would be easy to add this functionality to Wegue. Based on a new config option the [DragAndDrop interaction](https://openlayers.org/en/latest/apidoc/module-ol_interaction_DragAndDrop-DragAndDrop.html) could be added to the OL map within the Wegue map component.

See the official OL example as inspiration: https://openlayers.org/en/latest/examples/drag-and-drop.html

**Comment by justb4** [comment]
Nice feature, works for me for with KML, GeoJSON and GPX files

Suggestions:

* sometimes it is an option to replace the data i.s.o. adding to the Layer, but you would need user-interaction or a config option
* is it an idea to show the added Layer in the LayerList?  As config option (`displayInLayerList`, now hardcoded `false`). One could also configure the Layer name.

**Comment by chrismayer** [comment]
Done with #155

**Comment by JakobMiksch** [comment]
Shall we close this issue then?
